#!/usr/bin/env bash
cd /Users/ikennanokpala/repo/vagrant
# Stop and remove all containers
script/vagrant/docker_clean
# login to docker index
script/vagrant/docker_login
# Build the RabbitMQ container
docker build --tag=rabbitmq docker/rabbitmq
# Build main web project
docker build --tag=web .
